Repository cert-manager/trust-manager, pull requests merged in 2022-08, with the labels that each got.

#47 add restrictive securitycontext for controller pod
  deploy/charts/trust/templates/deployment.yaml
Labels: dco-signoff: yes, approved, lgtm, size/S

#48 Updates Helm chart version to v0.1.2
  deploy/charts/trust/Chart.yaml
  deploy/charts/trust/README.md
Labels: dco-signoff: yes, approved, size/XS, lgtm

#50 Update go to v1.19
  Dockerfile
  go.mod
  hack/tools/go.mod
Labels: dco-signoff: yes, approved, size/XS, lgtm

#51 Use `FROM scratch` for base image
  Dockerfile
Labels: dco-signoff: yes, approved, size/XS, lgtm

#32 Remove same bundle target key validation check
  pkg/webhook/validation.go
  pkg/webhook/validation_test.go
  pkg/webhook/webhook.go
Labels: dco-signoff: yes, approved, size/M, lgtm

#52 Update tag to v0.2.0 ready for release
  Makefile
  deploy/charts/trust/Chart.yaml
  deploy/charts/trust/README.md
  deploy/charts/trust/values.yaml
Labels: dco-signoff: yes, approved, lgtm, size/S
