Repository cert-manager/trust-manager, pull requests merged in 2022-05, with the labels that each got.

#22 Updates reference to jetstack/cert-manager to cert-manager/cert-manager in SECURITY.md
  SECURITY.md
Labels: dco-signoff: yes, approved, size/XS, lgtm

#21 Makefile: go vet
  Makefile
  hack/boilerplate/boilerplate.py
  pkg/bundle/bundle_test.go
  pkg/bundle/controller.go
  pkg/bundle/sync_test.go
  pkg/bundle/util.go
  pkg/bundle/util_test.go
  pkg/webhook/validation_test.go
  test/env/data.go
Labels: dco-signoff: yes, approved, size/L, lgtm

#19 Updates go modules and updates go version to v1.18
  Makefile
  go.mod
  go.sum
  hack/bin/tools.go
Labels: dco-signoff: yes, approved, lgtm, size/XL

#30 Use smaller cert-manager logo
  README.md
Labels: dco-signoff: yes, approved, size/XS, lgtm
