Repository cert-manager/trust-manager, pull requests merged in 2022-11, with the labels that each got.

#64 Rename to trust-manager
  Dockerfile
  Makefile
  README.md
  cmd/app/app.go
  cmd/app/options/options.go
  cmd/main.go
  deploy/charts/trust-manager/Chart.yaml
  deploy/charts/trust-manager/README.md
  deploy/charts/trust-manager/templates/_helpers.tpl
  deploy/charts/trust-manager/templates/certificate.yaml
  deploy/charts/trust-manager/templates/clusterrole.yaml
  deploy/charts/trust-manager/templates/clusterrolebinding.yaml
  deploy/charts/trust-manager/templates/deployment.yaml
  deploy/charts/trust-manager/templates/metrics-service.yaml
  deploy/charts/trust-manager/templates/metrics-servicemonitor.yaml
  deploy/charts/trust-manager/templates/role.yaml
  deploy/charts/trust-manager/templates/rolebinding.yaml
  deploy/charts/trust-manager/templates/serviceaccount.yaml
  deploy/charts/trust-manager/templates/trust.cert-manager.io_bundles.yaml
  deploy/charts/trust-manager/templates/webhook.yaml
  deploy/charts/trust-manager/values.yaml
  deploy/charts/trust/templates/certificate.yaml
  design/20210715.bundle-crd.md
  go.mod
  hack/ci/create-cluster.sh
  hack/update-codegen.sh
  hack/verify-helm-docs.sh
  pkg/apis/trust/v1alpha1/register.go
  pkg/bundle/bundle.go
  pkg/bundle/bundle_test.go
  pkg/bundle/controller.go
  pkg/bundle/sync.go
  pkg/bundle/sync_test.go
  pkg/bundle/test/integration.go
  pkg/bundle/test/integration_test.go
  pkg/bundle/test/suite.go
  pkg/bundle/util.go
  pkg/bundle/util_test.go
  pkg/webhook/validation.go
  pkg/webhook/validation_test.go
  test/env/data.go
  test/gen/bundle.go
  test/smoke/config/config.go
  test/smoke/smoke.go
  test/smoke/smoke_test.go
  test/smoke/suite.go
Labels: dco-signoff: yes, approved, size/L, lgtm

#65 Update Certificate resource to include issuerRef and group.
  deploy/charts/trust-manager/Chart.yaml
  deploy/charts/trust-manager/README.md
  deploy/charts/trust-manager/templates/certificate.yaml
Labels: dco-signoff: yes, approved, size/XS, lgtm, needs-ok-to-test

#61 #14 Updating the apiVersion to v2
  deploy/charts/trust-manager/Chart.yaml
Labels: dco-signoff: yes, approved, size/XS, lgtm, ok-to-test

#67 Release v0.3.0
  Makefile
  deploy/charts/trust-manager/Chart.yaml
  deploy/charts/trust-manager/README.md
  deploy/charts/trust-manager/values.yaml
Labels: dco-signoff: yes, approved, lgtm, size/S

#68 Prefix release version with 'v'
  Makefile
Labels: dco-signoff: yes, approved, size/XS, lgtm

#73 Add a static bundle sidecar container build
  Dockerfile
  Makefile
  bundles/debian/Containerfile
  bundles/debian/build.sh
  bundles/debian/go.mod
  bundles/debian/go.sum
  bundles/debian/main.go
  gcb/ci-update-debian-bundle.yaml
  hack/update-debian-ca-bundle.sh
  hack/wait-for-buildx.sh
  make/image-bundle-debian.mk
Labels: dco-signoff: yes, approved, lgtm, size/XL

#74 Update docker config to use a trust-manager-specific token
  gcb/ci-update-debian-bundle.yaml
Labels: dco-signoff: yes, approved, lgtm, size/S
