Repository cert-manager/trust-manager, pull requests merged in 2022-07, with the labels that each got.

#38 Add chart building + ensure BINDIR is created when running targets
  Makefile
Labels: dco-signoff: yes, approved, size/M, lgtm

#37 Bundle: `namespaceSelector`
  deploy/charts/trust/templates/clusterrole.yaml
  deploy/charts/trust/templates/trust.cert-manager.io_bundles.yaml
  pkg/apis/trust/v1alpha1/types_bundle.go
  pkg/apis/trust/v1alpha1/zz_generated.deepcopy.go
  pkg/bundle/bundle.go
  pkg/bundle/bundle_test.go
  pkg/bundle/sync.go
  pkg/bundle/sync_test.go
  pkg/bundle/test/suite.go
  pkg/webhook/validation.go
  pkg/webhook/validation_test.go
  test/env/data.go
  test/gen/bundle.go
  test/smoke/suite.go
Labels: dco-signoff: yes, approved, lgtm, size/XL

#41 Increase timeout for bundle integration tests for desired state from 10s to 30s
  pkg/bundle/test/suite.go
Labels: dco-signoff: yes, approved, size/XS, lgtm
