Repository cert-manager/trust-manager, pull requests merged in 2022-12, with the labels that each got.

#75 Add PEM verification function
  pkg/bundle/bundle.go
  pkg/bundle/bundle_test.go
  pkg/bundle/sync.go
  pkg/bundle/sync_test.go
  pkg/bundle/test/suite.go
  pkg/util/pem.go
  pkg/util/pem_test.go
  pkg/webhook/validation_test.go
  test/dummy/certificates.go
  test/env/data.go
  test/smoke/suite.go
Labels: dco-signoff: yes, approved, lgtm, size/XL

#77 Rename debian 'bundle' to 'package' / 'trust-package'
  Makefile
  gcb/ci-update-debian-trust-package.yaml
  hack/update-debian-trust-package.sh
  make/image-bundle-debian.mk
  make/trust-package-debian.mk
  trust-packages/README.md
  trust-packages/debian/Containerfile
  trust-packages/debian/README.md
  trust-packages/debian/build.sh
  trust-packages/debian/go.mod
  trust-packages/debian/go.sum
  trust-packages/debian/main.go
Labels: dco-signoff: yes, approved, size/L, lgtm

#70 Put seccomp behind a flag
  deploy/charts/trust-manager/README.md
  deploy/charts/trust-manager/templates/deployment.yaml
  deploy/charts/trust-manager/values.yaml
Labels: dco-signoff: yes, approved, size/XS, lgtm, ok-to-test

#78 fix broken link and old name references
  README.md
Labels: dco-signoff: yes, approved, size/XS, lgtm, ok-to-test

#80 Fix incorrect variable reference which was missed in #77
  SECURITY.md
  make/trust-package-debian.mk
Labels: dco-signoff: yes, approved, size/XS, lgtm

#79 Pass GOPROXY to build environment
  Dockerfile
  Makefile
  make/trust-package-debian.mk
  trust-packages/debian/Containerfile
Labels: dco-signoff: yes, approved, lgtm, size/S

#82 Various makefile updates / improvements
  Makefile
  make/trust-manager-build.mk
  test/integration/bundle/integration.go
  test/integration/bundle/integration_test.go
  test/integration/bundle/suite.go
Labels: dco-signoff: yes, approved, size/M, lgtm

#84 Fix logic error in trust-manager tests
  test/env/data.go
Labels: dco-signoff: yes, approved, size/XS, lgtm
