Repository cert-manager/trust-manager, pull requests merged in 2023-04, with the labels that each got.

#122 Add support for JKS truststores
  deploy/charts/trust-manager/templates/trust.cert-manager.io_bundles.yaml
  deploy/crds/trust.cert-manager.io_bundles.yaml
  go.mod
  go.sum
  pkg/apis/trust/v1alpha1/types_bundle.go
  pkg/apis/trust/v1alpha1/zz_generated.deepcopy.go
  pkg/bundle/bundle.go
  pkg/bundle/bundle_test.go
  pkg/bundle/sync.go
  pkg/bundle/sync_test.go
  pkg/webhook/validation.go
  pkg/webhook/validation_test.go
  test/gen/bundle.go
Labels: dco-signoff: yes, approved, size/L, lgtm, ok-to-test

#124 Minor restructure for ko compatibility
  Makefile
  cmd/trust-manager/app/app.go
  cmd/trust-manager/app/options/options.go
  cmd/trust-manager/main.go
Labels: dco-signoff: yes, approved, size/XS, lgtm, ok-to-test

#125 Bump to v0.5.0-beta.0 for release
  Dockerfile
  Makefile
  deploy/charts/trust-manager/Chart.yaml
  deploy/charts/trust-manager/README.md
  deploy/charts/trust-manager/values.yaml
Labels: dco-signoff: yes, approved, lgtm, size/S

#117 fixes #13 - Allow node selection based on nodeSelector, tolerations, affinities and topologySpreadConstraints
  deploy/charts/trust-manager/README.md
  deploy/charts/trust-manager/templates/deployment.yaml
  deploy/charts/trust-manager/values.yaml
Labels: dco-signoff: yes, approved, size/M, lgtm, ok-to-test

#121 helm: make installation of default trust package optional
  deploy/charts/trust-manager/README.md
  deploy/charts/trust-manager/templates/NOTES.txt
  deploy/charts/trust-manager/templates/deployment.yaml
  deploy/charts/trust-manager/values.yaml
Labels: dco-signoff: yes, approved, lgtm, ok-to-test, size/S
