Repository cert-manager/trust-manager, pull requests merged in 2023-01, with the labels that each got.

#83 trivial: remove second definition of _COMMA
  make/trust-package-debian.mk
Labels: dco-signoff: yes, approved, size/XS, lgtm

#85 Upgrade to ginkgo v2 + refactor several aspects of integration tests
  Makefile
  go.mod
  go.sum
  hack/bin/tools.go
  hack/ci/create-cluster.sh
  hack/ci/run-smoke-test.sh
  test/env/data.go
  test/env/ginkgo.go
  test/integration/bundle/integration.go
  test/integration/bundle/suite.go
  test/smoke/smoke.go
  test/smoke/suite.go
Labels: dco-signoff: yes, approved, lgtm, size/XL

#46 Bundles with a sidecar container
  Makefile
  cmd/app/options/options.go
  deploy/charts/trust-manager/README.md
  deploy/charts/trust-manager/templates/deployment.yaml
  deploy/charts/trust-manager/templates/trust.cert-manager.io_bundles.yaml
  deploy/charts/trust-manager/values.yaml
  pkg/apis/trust/v1alpha1/types_bundle.go
  pkg/apis/trust/v1alpha1/zz_generated.deepcopy.go
  pkg/bundle/bundle.go
  pkg/bundle/bundle_test.go
  pkg/bundle/controller.go
  pkg/bundle/sync.go
  pkg/bundle/sync_test.go
  pkg/bundle/util.go
  pkg/bundle/util_test.go
  pkg/fspkg/package.go
  pkg/fspkg/package_test.go
  pkg/webhook/validation.go
  pkg/webhook/validation_test.go
  test/dummy/certificates.go
  test/env/data.go
  test/gen/bundle.go
  test/integration/bundle/suite.go
  test/smoke/suite.go
Labels: dco-signoff: yes, approved, lgtm, size/XL

#90 Fix the MultiScopedCache
  cmd/app/app.go
  pkg/bundle/cache/cache.go
  pkg/bundle/controller.go
  test/integration/bundle/cache_test.go
Labels: dco-signoff: yes, approved, size/L, lgtm

#88 Remove type from trust packages + add validation on package build
  Makefile
  cmd/app/app.go
  cmd/validate-trust-package/main.go
  hack/boilerplate/boilerplate.py
  trust-packages/debian/build.sh
Labels: dco-signoff: yes, approved, size/M, lgtm

#93 Validate CA package during build
  trust-packages/debian/Containerfile
  trust-packages/debian/build.sh
Labels: dco-signoff: yes, approved, lgtm, size/S

#92 Fix non-cached client
  pkg/bundle/bundle.go
  pkg/bundle/bundle_test.go
  pkg/bundle/cache/cache.go
  pkg/bundle/controller.go
  pkg/bundle/sync.go
  pkg/bundle/sync_test.go
Labels: dco-signoff: yes, approved, size/L, lgtm

#95 fix typo
  test/integration/bundle/suite.go
Labels: dco-signoff: yes, approved, size/XS, lgtm

#97 Helm tweaks + better makefile "ensure"
  Makefile
  deploy/charts/trust-manager/Chart.yaml
  deploy/charts/trust-manager/README.md
  deploy/charts/trust-manager/templates/NOTES.txt
  make/color.mk
  test/smoke/config/config.go
  test/smoke/smoke.go
  test/smoke/smoke_test.go
Labels: dco-signoff: yes, approved, size/L, lgtm

#103 Readme tweak taken from website#1160
  README.md
Labels: dco-signoff: yes, approved, size/M, lgtm

#104 Rename '_test.go' suffix to test file
  test/smoke/suite_test.go
Labels: dco-signoff: yes, approved, size/XS, lgtm

#105 Remove deprecated v1beta1 admission review version
  deploy/charts/trust-manager/templates/webhook.yaml
Labels: dco-signoff: yes, approved, size/XS, lgtm

#107 Use a source and a target cache instead of a MultiScopedCache
  cmd/app/app.go
  pkg/bundle/bundle.go
  pkg/bundle/bundle_test.go
  pkg/bundle/cache/cache.go
  pkg/bundle/controller.go
  pkg/bundle/sync.go
  pkg/bundle/sync_test.go
  test/integration/bundle/cache_test.go
  test/integration/bundle/suite.go
Labels: dco-signoff: yes, approved, lgtm, size/XL
