Repository cert-manager/trust-manager, pull requests merged in 2023-10, with the labels that each got.

#186 Bump version to v0.7.0-alpha.1
  Makefile
  deploy/charts/trust-manager/Chart.yaml
  deploy/charts/trust-manager/README.md
Labels: dco-signoff: yes, approved, size/XS, lgtm

#191 fix: add missing RBAC for CSA->SSA migration of bundles/status
  deploy/charts/trust-manager/templates/clusterrole.yaml
Labels: dco-signoff: yes, approved, size/XS, lgtm

#192 Update a couple of instances of the old project name
  deploy/charts/trust-manager/README.md
  deploy/charts/trust-manager/values.yaml
Labels: dco-signoff: yes, approved, lgtm, size/S

#194 Vendor dependencies correctly
  Dockerfile
  Makefile
  hack/update-codegen.sh
Labels: dco-signoff: yes, approved, size/L, lgtm

#156 Allow enabling hostNetwork mode in Helm chart
  deploy/charts/trust-manager/README.md
  deploy/charts/trust-manager/templates/deployment.yaml
  deploy/charts/trust-manager/values.yaml
Labels: dco-signoff: yes, approved, size/XS, lgtm, ok-to-test

#198 allow setting namespace for helm chart
  deploy/charts/trust-manager/README.md
  deploy/charts/trust-manager/templates/_helpers.tpl
  deploy/charts/trust-manager/templates/certificate.yaml
  deploy/charts/trust-manager/templates/clusterrolebinding.yaml
  deploy/charts/trust-manager/templates/deployment.yaml
  deploy/charts/trust-manager/templates/metrics-service.yaml
  deploy/charts/trust-manager/templates/metrics-servicemonitor.yaml
  deploy/charts/trust-manager/templates/rolebinding.yaml
  deploy/charts/trust-manager/templates/serviceaccount.yaml
  deploy/charts/trust-manager/templates/webhook.yaml
  deploy/charts/trust-manager/values.yaml
Labels: dco-signoff: yes, approved, size/M, lgtm, ok-to-test

#193 feat: support secret as a target
  Makefile
  deploy/charts/trust-manager/README.md
  deploy/charts/trust-manager/templates/clusterrole.yaml
  deploy/charts/trust-manager/templates/trust.cert-manager.io_bundles.yaml
  deploy/charts/trust-manager/values.yaml
  deploy/crds/trust.cert-manager.io_bundles.yaml
  pkg/apis/trust/v1alpha1/types_bundle.go
  pkg/apis/trust/v1alpha1/zz_generated.deepcopy.go
  pkg/bundle/bundle.go
  pkg/bundle/controller.go
  pkg/bundle/internal/ssa_client/configmap.go
  pkg/bundle/sync.go
  pkg/bundle/sync_test.go
  pkg/webhook/validation.go
  pkg/webhook/validation_test.go
  test/env/data.go
  test/integration/bundle/suite.go
  test/smoke/suite_test.go
Labels: dco-signoff: yes, approved, lgtm, ok-to-test, size/XXL

#200 Fix build on macOS / values.yaml wording tweaks
  Makefile
  deploy/charts/trust-manager/README.md
  deploy/charts/trust-manager/values.yaml
Labels: dco-signoff: yes, approved, lgtm, size/S

#118 Make seccompProfile optional in initContainer
  deploy/charts/trust-manager/templates/deployment.yaml
Labels: dco-signoff: yes, approved, size/XS, lgtm, ok-to-test

#201 add a CN for the trust-manager certificate
  deploy/charts/trust-manager/templates/certificate.yaml
Labels: dco-signoff: yes, approved, size/XS, lgtm

#203 Preparing release v0.7.0-alpha.2
  Makefile
  deploy/charts/trust-manager/Chart.yaml
  deploy/charts/trust-manager/README.md
Labels: dco-signoff: yes, approved, size/XS, lgtm

#204 Upgrade go to 1.21
  Dockerfile
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  trust-packages/debian/Containerfile
  trust-packages/debian/go.mod
Labels: dco-signoff: yes, approved, lgtm, size/S

#176 Allow configuring of the priorityClass
  deploy/charts/trust-manager/README.md
  deploy/charts/trust-manager/templates/deployment.yaml
  deploy/charts/trust-manager/values.yaml
Labels: dco-signoff: yes, approved, size/XS, lgtm, ok-to-test

#209 Remove patch versions from go directives
  go.mod
  hack/tools/go.mod
  trust-packages/debian/go.mod
Labels: dco-signoff: yes, approved, size/XS, lgtm

#208 [release-0.6] Bump deps to fix CVEs
  Makefile
  deploy/charts/trust-manager/Chart.yaml
  deploy/charts/trust-manager/README.md
  deploy/charts/trust-manager/values.yaml
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: dco-signoff: yes, approved, size/M, lgtm

#210 Cleanup patch functions Secret and ConfigMap targets
  pkg/bundle/sync.go
Labels: dco-signoff: yes, approved, lgtm, size/S

#211 BUGFIX: support switching between target types
  pkg/bundle/bundle.go
  pkg/bundle/bundle_test.go
Labels: dco-signoff: yes, approved, size/L, lgtm

#207 fix: should not have have read access to all secrets when secret targets disabled
  cmd/trust-manager/app/app.go
  cmd/trust-manager/app/options/options.go
  deploy/charts/trust-manager/README.md
  deploy/charts/trust-manager/templates/clusterrole.yaml
  deploy/charts/trust-manager/templates/deployment.yaml
  deploy/charts/trust-manager/values.yaml
  pkg/bundle/bundle.go
  pkg/bundle/bundle_test.go
  pkg/bundle/controller.go
Labels: dco-signoff: yes, approved, size/L, lgtm

#213 Bump release version to v0.7.0-alpha.3
  Makefile
  deploy/charts/trust-manager/Chart.yaml
  deploy/charts/trust-manager/README.md
Labels: dco-signoff: yes, approved, size/XS, lgtm

#216 Add erikgb to project approvers
  OWNERS
Labels: dco-signoff: yes, approved, size/XS, lgtm

#215 Use proper namespace for webhook
  deploy/charts/trust-manager/templates/webhook.yaml
Labels: dco-signoff: yes, approved, size/XS, lgtm, ok-to-test

#218 FIX: For CSA to SSA migration, we need UPDATE permission on the resource (not the sub-resource)
  deploy/charts/trust-manager/templates/clusterrole.yaml
Labels: dco-signoff: yes, approved, size/XS, lgtm

#219 Prepare release v0.7.0
  Makefile
  deploy/charts/trust-manager/Chart.yaml
  deploy/charts/trust-manager/README.md
Labels: dco-signoff: yes, approved, size/XS, lgtm

#116 feat: add support for additional pod annotations/labels
  deploy/charts/trust-manager/README.md
  deploy/charts/trust-manager/templates/deployment.yaml
  deploy/charts/trust-manager/values.yaml
Labels: dco-signoff: yes, approved, lgtm, ok-to-test, size/S
