Repository cert-manager/trust-manager, pull requests merged in 2023-05, with the labels that each got.

#127 Use ordered aliases when creating JKS files
  pkg/bundle/sync.go
Labels: dco-signoff: yes, approved, size/XS, lgtm

#126 Add descriptions for some helm chart fields
  deploy/charts/trust-manager/README.md
  deploy/charts/trust-manager/values.yaml
Labels: dco-signoff: yes, approved, lgtm, size/S

#123 Explicitly define resource namespaces in Helm chart
  deploy/charts/trust-manager/templates/certificate.yaml
  deploy/charts/trust-manager/templates/deployment.yaml
  deploy/charts/trust-manager/templates/metrics-service.yaml
  deploy/charts/trust-manager/templates/metrics-servicemonitor.yaml
  deploy/charts/trust-manager/templates/serviceaccount.yaml
  deploy/charts/trust-manager/templates/webhook.yaml
Labels: dco-signoff: yes, approved, size/XS, lgtm

#129 Ensure unique aliases in JKS files
  pkg/apis/trust/v1alpha1/types_bundle.go
  pkg/bundle/sync.go
  pkg/bundle/sync_test.go
  pkg/util/pem.go
  test/dummy/certificates.go
  test/env/data.go
  test/integration/bundle/suite.go
Labels: dco-signoff: yes, approved, size/L, lgtm

#134 Bump version to v0.5.0-beta.1
  Makefile
  deploy/charts/trust-manager/Chart.yaml
  deploy/charts/trust-manager/README.md
  deploy/charts/trust-manager/values.yaml
Labels: dco-signoff: yes, approved, lgtm, size/S

#137 Add description for JKS field for better docs
  pkg/apis/trust/v1alpha1/types_bundle.go
Labels: dco-signoff: yes, approved, size/XS, lgtm
