Repository cert-manager/trust-manager, pull requests merged in 2023-08, with the labels that each got.

#158 Add support for approver policy
  deploy/charts/trust-manager/README.md
  deploy/charts/trust-manager/templates/certificate.yaml
  deploy/charts/trust-manager/values.yaml
Labels: dco-signoff: yes, approved, size/M, lgtm

#143 Setting useDefaultCAs: false no longer causes failures
  pkg/bundle/sync.go
  pkg/webhook/validation.go
  pkg/webhook/validation_test.go
Labels: dco-signoff: yes, approved, size/L, lgtm, ok-to-test

#146 Fix code generation
  deploy/charts/trust-manager/templates/trust.cert-manager.io_bundles.yaml
  deploy/crds/trust.cert-manager.io_bundles.yaml
  hack/boilerplate/boilerplate.go.txt
  hack/update-codegen.sh
Labels: dco-signoff: yes, approved, lgtm, ok-to-test, size/S

#160 Bump versions ready for v0.6.0
  Makefile
  deploy/charts/trust-manager/Chart.yaml
  deploy/charts/trust-manager/README.md
  deploy/charts/trust-manager/values.yaml
Labels: dco-signoff: yes, approved, lgtm, size/S

#154 Add new optional registry and digest Helm values
  deploy/charts/trust-manager/README.md
  deploy/charts/trust-manager/templates/deployment.yaml
  deploy/charts/trust-manager/values.yaml
Labels: dco-signoff: yes, approved, lgtm, ok-to-test, size/S

#162 Refactor CM binary data reconcile preparing for PKCS#12 support
  pkg/bundle/sync.go
  pkg/bundle/sync_test.go
Labels: dco-signoff: yes, approved, size/M, lgtm, ok-to-test

#163 Add support for PKCS12 truststores
  go.mod
  go.sum
  pkg/apis/trust/v1alpha1/types_bundle.go
  pkg/bundle/bundle.go
  pkg/bundle/sync.go
  pkg/bundle/sync_test.go
  pkg/util/pem.go
  pkg/webhook/validation.go
  pkg/webhook/validation_test.go
Labels: dco-signoff: yes, approved, size/L, lgtm, ok-to-test

#164 Add support for PKCS12 truststores (update CRD)
  deploy/charts/trust-manager/templates/trust.cert-manager.io_bundles.yaml
  deploy/crds/trust.cert-manager.io_bundles.yaml
Labels: dco-signoff: yes, approved, size/M, lgtm, ok-to-test

#166 ci: verify all generated files are up-to-date
  .gitignore
  Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  hack/update-codegen.sh
  hack/util/verify.sh
  hack/verify-helm-docs.sh
  pkg/apis/trust/v1alpha1/doc.go
  pkg/apis/trust/v1alpha1/types_bundle.go
  pkg/apis/trust/v1alpha1/zz_generated.deepcopy.go
Labels: dco-signoff: yes, approved, size/L, lgtm, needs-ok-to-test

#169 Filter resources triggered by namespace
  pkg/bundle/bundle.go
  pkg/bundle/bundle_test.go
  pkg/bundle/controller.go
Labels: dco-signoff: yes, approved, size/M, lgtm

#171 Move from k8s.io/utils/pointer to k8s.io/utils/ptr
  pkg/bundle/bundle_test.go
  pkg/bundle/sync_test.go
  pkg/bundle/util_test.go
  pkg/webhook/validation_test.go
  test/gen/bundle.go
  test/integration/bundle/integration.go
  test/integration/bundle/suite.go
  test/smoke/suite_test.go
Labels: dco-signoff: yes, approved, size/L, lgtm

#170 Refactor util functions in preparation for SSA
  pkg/apis/trust/v1alpha1/types_bundle.go
  pkg/bundle/bundle.go
  pkg/bundle/bundle_test.go
  pkg/bundle/util.go
  pkg/bundle/util_test.go
  test/env/data.go
Labels: dco-signoff: yes, approved, size/L, lgtm

#173 Fix BundleStatus go definition in preparation for SSA
  deploy/charts/trust-manager/templates/trust.cert-manager.io_bundles.yaml
  deploy/crds/trust.cert-manager.io_bundles.yaml
  pkg/apis/trust/v1alpha1/types_bundle.go
Labels: dco-signoff: yes, approved, lgtm, size/S
