Repository cert-manager/trust-manager, pull requests merged in 2023-09, with the labels that each got.

#89 Use SSA
  cmd/trust-manager/app/app.go
  deploy/charts/trust-manager/Chart.yaml
  deploy/charts/trust-manager/README.md
  deploy/charts/trust-manager/templates/clusterrole.yaml
  go.mod
  go.sum
  pkg/apis/trust/v1alpha1/types_bundle.go
  pkg/bundle/bundle.go
  pkg/bundle/bundle_test.go
  pkg/bundle/controller.go
  pkg/bundle/internal/ssa_client/bundle_status.go
  pkg/bundle/internal/ssa_client/configmap.go
  pkg/bundle/internal/ssa_client/patch.go
  pkg/bundle/sync.go
  pkg/bundle/sync_test.go
  test/integration/bundle/integration.go
  test/integration/bundle/suite.go
Labels: dco-signoff: yes, approved, lgtm, size/XXL

#177 Release v0.7.0-alpha.0
  Makefile
  deploy/charts/trust-manager/Chart.yaml
  deploy/charts/trust-manager/README.md
  deploy/charts/trust-manager/values.yaml
Labels: dco-signoff: yes, approved, lgtm, size/S

#174 Allow user to specify the name of cert-manager's ServiceAccount
  deploy/charts/trust-manager/README.md
  deploy/charts/trust-manager/templates/certificate.yaml
  deploy/charts/trust-manager/values.yaml
Labels: dco-signoff: yes, approved, lgtm, size/S

#179 HELM: add options for configuring image
  deploy/charts/trust-manager/README.md
  deploy/charts/trust-manager/templates/_helpers.tpl
  deploy/charts/trust-manager/templates/deployment.yaml
  deploy/charts/trust-manager/values.yaml
Labels: dco-signoff: yes, approved, size/M, lgtm

#178 BUGFIX: fix migration from csa to ssa
  pkg/bundle/bundle.go
  pkg/bundle/controller.go
  pkg/bundle/sync.go
  test/integration/bundle/suite.go
Labels: dco-signoff: yes, approved, size/L, lgtm

#182 Update kubeVersion to allow for eks metadata at end of kubernetes ver…
  deploy/charts/trust-manager/Chart.yaml
  deploy/charts/trust-manager/README.md
Labels: dco-signoff: yes, approved, size/XS, lgtm, ok-to-test

#185 Refactor bundle controller setup
  pkg/bundle/controller.go
Labels: dco-signoff: yes, approved, size/L, lgtm

#188 Cleanup controller bootstrap
  cmd/trust-manager/app/app.go
Labels: dco-signoff: yes, approved, lgtm, size/S

#184 Add certificates deduplication feature
  pkg/util/cert_pool.go
  pkg/util/cert_pool_test.go
  pkg/util/pem.go
  test/dummy/certificates.go
Labels: dco-signoff: yes, approved, size/L, lgtm, ok-to-test

#189 Fix SSA migration field managers
  pkg/bundle/bundle.go
  pkg/bundle/sync.go
Labels: dco-signoff: yes, approved, lgtm, size/S
