Repository cert-manager/trust-manager, pull requests merged in 2023-11, with the labels that each got.

#225 Allow permissions to put the leases in the trust-manager namespace, not the trust namespace
  cmd/trust-manager/app/app.go
  deploy/charts/trust-manager/templates/role.yaml
  deploy/charts/trust-manager/templates/rolebinding.yaml
Labels: dco-signoff: yes, approved, lgtm, ok-to-test, size/S

#228 Tweak readme to encourage use
  README.md
Labels: dco-signoff: yes, approved, lgtm, size/S

#217 chore: generate applyconfigurations for custom resources
  Makefile
  go.mod
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  pkg/apis/trust/v1alpha1/types_bundle.go
  pkg/applyconfigurations/internal/internal.go
  pkg/applyconfigurations/trust/v1alpha1/additionalformats.go
  pkg/applyconfigurations/trust/v1alpha1/bundle.go
  pkg/applyconfigurations/trust/v1alpha1/bundlecondition.go
  pkg/applyconfigurations/trust/v1alpha1/bundlesource.go
  pkg/applyconfigurations/trust/v1alpha1/bundlespec.go
  pkg/applyconfigurations/trust/v1alpha1/bundlestatus.go
  pkg/applyconfigurations/trust/v1alpha1/bundletarget.go
  pkg/applyconfigurations/trust/v1alpha1/keyselector.go
  pkg/applyconfigurations/trust/v1alpha1/namespaceselector.go
  pkg/applyconfigurations/trust/v1alpha1/sourceobjectkeyselector.go
  pkg/applyconfigurations/utils.go
Labels: dco-signoff: yes, approved, lgtm, size/XL

#230 chore!: remove .status.target field from Bundle API
  deploy/charts/trust-manager/templates/trust.cert-manager.io_bundles.yaml
  deploy/crds/trust.cert-manager.io_bundles.yaml
  pkg/apis/trust/v1alpha1/types_bundle.go
  pkg/apis/trust/v1alpha1/zz_generated.deepcopy.go
  pkg/applyconfigurations/trust/v1alpha1/bundlestatus.go
  pkg/bundle/bundle.go
  pkg/bundle/bundle_test.go
  pkg/bundle/sync.go
  test/env/data.go
  test/integration/bundle/suite.go
Labels: dco-signoff: yes, approved, size/L, lgtm

#247 Improve package CI error handling
  Makefile
  hack/update-debian-trust-package.sh
  make/trust-package-debian.mk
Labels: dco-signoff: yes, approved, lgtm, size/S

#241 fix: should encode additional target format just once per bundle reconcile
  pkg/bundle/bundle.go
  pkg/bundle/sync.go
  pkg/bundle/sync_test.go
Labels: dco-signoff: yes, approved, size/L, lgtm

#248 Fix apply configuration generation on macOS
  Makefile
Labels: dco-signoff: yes, approved, size/XS, lgtm

#250 Better handling of local arch differences
  Makefile
  make/trust-manager-build.mk
  make/trust-package-debian.mk
Labels: dco-signoff: yes, approved, lgtm, size/S
