Repository cert-manager/trust-manager, pull requests merged in 2024-11, with the labels that each got.

#469 feat(helm): add secretTemplate-ing to certificate
  deploy/charts/trust-manager/README.md
  deploy/charts/trust-manager/templates/certificate.yaml
  deploy/charts/trust-manager/values.schema.json
  deploy/charts/trust-manager/values.yaml
Labels: dco-signoff: yes, approved, size/M, lgtm, ok-to-test

#467 Feat: Add port naming for podMonitor support
  deploy/charts/trust-manager/templates/deployment.yaml
Labels: dco-signoff: yes, approved, size/XS, lgtm, ok-to-test

#474 Fix crd validation: Key should not be required anymore in bundle source resources
  deploy/charts/trust-manager/templates/crd-trust.cert-manager.io_bundles.yaml
  docs/api/api.md
  pkg/apis/trust/v1alpha1/types_bundle.go
  pkg/apis/trust/v1alpha1/zz_generated.deepcopy.go
  pkg/bundle/bundle_test.go
  pkg/bundle/source_test.go
  pkg/webhook/validation_test.go
  test/env/data.go
  test/integration/bundle/suite.go
Labels: dco-signoff: yes, approved, size/L, lgtm, ok-to-test

#480 Fix issue with updating of JKS/PKCS targets when password changes #449 (review)
  pkg/bundle/bundle_test.go
  pkg/bundle/internal/target/target.go
  pkg/bundle/internal/target/target_test.go
Labels: dco-signoff: yes, approved, lgtm, size/XL

#449 Fix issue with updating of JKS/PKCS targets when password changes
  docs/api/api.md
  pkg/apis/trust/v1alpha1/types_bundle.go
  pkg/bundle/bundle_test.go
  pkg/bundle/internal/target/target.go
Labels: dco-signoff: yes, approved, size/L, lgtm, do-not-merge/hold, ok-to-test

#477 Improve API specification
  deploy/charts/trust-manager/templates/crd-trust.cert-manager.io_bundles.yaml
  docs/api/api.md
  pkg/apis/trust/v1alpha1/types_bundle.go
Labels: dco-signoff: yes, approved, size/M, lgtm

#440 refactor: more generic target handling
  pkg/bundle/bundle.go
  pkg/bundle/internal/ssa_client/bundle_status.go
  pkg/bundle/internal/ssa_client/configmap.go
  pkg/bundle/internal/ssa_client/patch.go
  pkg/bundle/internal/target/target.go
  pkg/bundle/internal/target/target_test.go
Labels: dco-signoff: yes, approved, size/L, lgtm

#476 feat: support namespaceSelector matchExpressions
  deploy/charts/trust-manager/templates/crd-trust.cert-manager.io_bundles.yaml
  docs/api/api.md
  pkg/apis/trust/v1alpha1/types_bundle.go
  pkg/apis/trust/v1alpha1/zz_generated.deepcopy.go
  pkg/bundle/bundle.go
  pkg/webhook/validation.go
  pkg/webhook/validation_test.go
  test/gen/bundle.go
  test/integration/bundle/suite.go
  test/smoke/suite_test.go
Labels: dco-signoff: yes, approved, size/L, lgtm

#490 Set dummy Helm chart versions
  deploy/charts/trust-manager/Chart.yaml
Labels: dco-signoff: yes, approved, size/XS, lgtm

#491 Remove generated api-docs
  docs/api/api.md
  klone.yaml
  make/_shared/api-docs/01_mod.mk
Labels: dco-signoff: yes, approved, lgtm, size/XL
