Repository cert-manager/trust-manager, pull requests merged in 2024-05, with the labels that each got.

#344 Fix Bundle target print column
  deploy/charts/trust-manager/templates/trust.cert-manager.io_bundles.yaml
  deploy/crds/trust.cert-manager.io_bundles.yaml
  pkg/apis/trust/v1alpha1/types_bundle.go
Labels: dco-signoff: yes, approved, lgtm, size/S

#319 Simplify managed fields upgrade from CSA to SSA
  deploy/charts/trust-manager/templates/clusterrole.yaml
  pkg/bundle/bundle.go
  pkg/bundle/controller.go
  pkg/bundle/sync.go
Labels: dco-signoff: yes, approved, size/L, lgtm

#352 Replace deprecated klog.New in tests with ktesting.NewTestContext
  pkg/bundle/bundle_test.go
  pkg/bundle/sync_test.go
  pkg/webhook/validation_test.go
  test/smoke/suite_test.go
Labels: dco-signoff: yes, approved, size/M, lgtm

#354 Add support for JSON logging format
  cmd/trust-manager/app/options/options.go
  deploy/charts/trust-manager/README.md
  deploy/charts/trust-manager/templates/deployment.yaml
  deploy/charts/trust-manager/values.schema.json
  deploy/charts/trust-manager/values.yaml
Labels: dco-signoff: yes, approved, size/M, lgtm

#356 Deduplicate code for syncing target configmaps and secrets
  pkg/bundle/bundle.go
Labels: dco-signoff: yes, approved, size/L, lgtm

#360 Fix all linter issues and un-ignore golanci-lint linter exceptions
  .golangci.yaml
  cmd/trust-manager/app/app.go
  cmd/trust-manager/app/options/options.go
  pkg/bundle/bundle.go
  pkg/bundle/internal/ssa_client/bundle_status.go
  pkg/bundle/sync.go
  pkg/bundle/util.go
  pkg/util/cert_pool.go
  pkg/util/pem.go
  pkg/util/pem_test.go
  pkg/webhook/validation.go
  pkg/webhook/validation_test.go
  pkg/webhook/webhook.go
  test/dummy/certificates.go
  test/env/data.go
  test/env/ginkgo.go
  test/integration/bundle/integration.go
  test/integration/bundle/suite.go
  test/smoke/smoke_test.go
  test/smoke/suite_test.go
Labels: dco-signoff: yes, approved, size/L, lgtm
