Repository cert-manager/trust-manager, pull requests merged in 2024-02, with the labels that each got.

#284 test: should test setBundleCondition as it's used
  pkg/bundle/util_test.go
Labels: dco-signoff: yes, approved, lgtm, size/S

#286 Upgrade tools
  deploy/charts/trust-manager/README.md
  deploy/charts/trust-manager/templates/trust.cert-manager.io_bundles.yaml
  deploy/crds/trust.cert-manager.io_bundles.yaml
  hack/tools/go.mod
  hack/tools/go.sum
Labels: dco-signoff: yes, approved, lgtm, size/XXL

#287 Update README.md and Chart.yaml
  deploy/charts/trust-manager/Chart.yaml
  deploy/charts/trust-manager/README.md
Labels: dco-signoff: yes, approved, size/M, lgtm

#288 Add 'crds.keep' options to generated CRDs
  Makefile
  deploy/charts/trust-manager/README.md
  deploy/charts/trust-manager/templates/trust.cert-manager.io_bundles.yaml
  deploy/charts/trust-manager/values.yaml
  hack/update-codegen.sh
Labels: dco-signoff: yes, approved, size/M, lgtm

#293 Add thatsmrtalbot as a reviewer
  OWNERS
Labels: dco-signoff: yes, approved, size/XS, lgtm

#289 Improve OCI image options' Helm README.md documentation
  deploy/charts/trust-manager/README.md
  deploy/charts/trust-manager/values.yaml
Labels: dco-signoff: yes, approved, size/L, lgtm

#292 Fix typo in Chart.yaml icon URL
  deploy/charts/trust-manager/Chart.yaml
Labels: dco-signoff: yes, approved, size/XS, lgtm

#290 Generate values.schema.json
  Makefile
  deploy/charts/trust-manager/README.md
  deploy/charts/trust-manager/values.schema.json
  deploy/charts/trust-manager/values.yaml
Labels: dco-signoff: yes, approved, lgtm, size/XL

#306 Helm: Uniformize all label include statements & add labels to pod template
  deploy/charts/trust-manager/templates/certificate.yaml
  deploy/charts/trust-manager/templates/clusterrole.yaml
  deploy/charts/trust-manager/templates/clusterrolebinding.yaml
  deploy/charts/trust-manager/templates/deployment.yaml
  deploy/charts/trust-manager/templates/metrics-service.yaml
  deploy/charts/trust-manager/templates/metrics-servicemonitor.yaml
  deploy/charts/trust-manager/templates/role.yaml
  deploy/charts/trust-manager/templates/rolebinding.yaml
  deploy/charts/trust-manager/templates/serviceaccount.yaml
  deploy/charts/trust-manager/templates/webhook.yaml
Labels: dco-signoff: yes, approved, size/M, lgtm

#307 Fix passwordless pkcs12 files for Java
  pkg/bundle/sync.go
Labels: dco-signoff: yes, approved, size/XS, lgtm

#308 Set a size limit on emptyDir
  deploy/charts/trust-manager/templates/deployment.yaml
Labels: dco-signoff: yes, approved, size/XS, lgtm

#303 Improve certificate deduplication operation
  pkg/bundle/sync.go
  pkg/bundle/sync_test.go
  pkg/util/cert_pool.go
  pkg/util/cert_pool_test.go
Labels: dco-signoff: yes, approved, size/L, lgtm, ok-to-test

#309 Production readiness Helm chart tweaks
  deploy/charts/trust-manager/README.md
  deploy/charts/trust-manager/templates/NOTES.txt
  deploy/charts/trust-manager/values.schema.json
  deploy/charts/trust-manager/values.yaml
Labels: dco-signoff: yes, approved, lgtm, size/S
