Repository cert-manager/trust-manager, pull requests merged in 2024-03, with the labels that each got.

#315 enable trust manager on s390x
  Makefile
Labels: dco-signoff: yes, approved, size/XS, lgtm, ok-to-test

#316 initContainer Resource Block: Fix #295 for merging
  deploy/charts/trust-manager/README.md
  deploy/charts/trust-manager/templates/deployment.yaml
  deploy/charts/trust-manager/values.schema.json
  deploy/charts/trust-manager/values.yaml
Labels: dco-signoff: yes, approved, size/M, lgtm

#317 Upgrade tool dependencies
  deploy/charts/trust-manager/values.schema.json
  hack/tools/go.mod
  hack/tools/go.sum
Labels: dco-signoff: yes, approved, lgtm, size/S

#314 Bump version for release, bump go to latest
  Dockerfile
  Makefile
  deploy/charts/trust-manager/Chart.yaml
  go.mod
Labels: dco-signoff: yes, approved, lgtm, size/S

#318 Bump toolchain to latest to address CVE-2024-24783
  go.mod
Labels: dco-signoff: yes, approved, size/XS, lgtm

#321 bump builder go to 1.22
  trust-packages/debian/Containerfile
Labels: dco-signoff: yes, approved, size/XS, lgtm

#325 [release-0.9] Bump builder go to 1.22
  trust-packages/debian/Containerfile
Labels: dco-signoff: yes, approved, size/XS, lgtm

#323 Also check for correct architectures in trust package build
  hack/update-debian-trust-package.sh
Labels: dco-signoff: yes, approved, size/M, lgtm

#330 Helm chart - document and add to schema nameOverride
  deploy/charts/trust-manager/README.md
  deploy/charts/trust-manager/values.schema.json
  deploy/charts/trust-manager/values.yaml
Labels: dco-signoff: yes, approved, lgtm, needs-ok-to-test, size/S

#331 [release-0.9] Backport name override
  deploy/charts/trust-manager/README.md
  deploy/charts/trust-manager/values.schema.json
  deploy/charts/trust-manager/values.yaml
Labels: dco-signoff: yes, approved, lgtm, size/S

#334 [release-0.9] bump chart / release versions
  Makefile
  deploy/charts/trust-manager/Chart.yaml
Labels: dco-signoff: yes, approved, size/XS, lgtm
