Repository cert-manager/trust-manager, pull requests merged in 2024-07, with the labels that each got.

#377 refactor: build bundle data from relevant spec
  pkg/bundle/bundle.go
  pkg/bundle/source.go
  pkg/bundle/source_test.go
Labels: dco-signoff: yes, approved, size/L, lgtm

#380 Sort certificates in bundles to ensure deterministic behaviour
  pkg/bundle/bundle_test.go
  pkg/bundle/source.go
  pkg/bundle/source_test.go
  test/dummy/certificates.go
  test/env/data.go
  test/integration/bundle/suite.go
  test/smoke/suite_test.go
Labels: dco-signoff: yes, approved, size/L, lgtm, ok-to-test

#337 feat(helm): dual-stack cluster service configuration
  deploy/charts/trust-manager/README.md
  deploy/charts/trust-manager/templates/metrics-service.yaml
  deploy/charts/trust-manager/templates/webhook.yaml
  deploy/charts/trust-manager/values.schema.json
  deploy/charts/trust-manager/values.yaml
Labels: dco-signoff: yes, approved, size/M, lgtm, ok-to-test

#385 Add flags to configure LeaseDuration and RenewDeadline
  cmd/trust-manager/app/app.go
  cmd/trust-manager/app/options/options.go
Labels: dco-signoff: yes, approved, lgtm, ok-to-test, size/S

#157 Add support for generating certificates with helm
  deploy/charts/trust-manager/README.md
  deploy/charts/trust-manager/templates/certificate.yaml
  deploy/charts/trust-manager/templates/deployment.yaml
  deploy/charts/trust-manager/templates/webhook.yaml
  deploy/charts/trust-manager/values.schema.json
  deploy/charts/trust-manager/values.yaml
Labels: dco-signoff: yes, approved, size/L, lgtm

#388 Expose leader election leaseDuration and renewDeadline in helm chart
  deploy/charts/trust-manager/README.md
  deploy/charts/trust-manager/templates/deployment.yaml
  deploy/charts/trust-manager/values.schema.json
  deploy/charts/trust-manager/values.yaml
Labels: dco-signoff: yes, approved, size/M, lgtm, ok-to-test

#392 [CI] Self-upgrade merging self-upgrade-main into main
  .github/workflows/govulncheck.yaml
  .github/workflows/make-self-upgrade.yaml
  klone.yaml
  make/_shared/go/base/.github/workflows/govulncheck.yaml
  make/_shared/repository-base/base/.github/workflows/make-self-upgrade.yaml
Labels: dco-signoff: yes, approved, size/M, lgtm

#393 refactor: simplify SSA patch calls
  pkg/bundle/bundle.go
  pkg/bundle/target.go
Labels: dco-signoff: yes, approved, lgtm, size/S

#394 refactor: move default truststore passwords to API
  docs/api/api.md
  pkg/apis/trust/v1alpha1/types_bundle.go
  pkg/bundle/bundle_test.go
  pkg/bundle/source.go
  pkg/bundle/source_test.go
  test/integration/bundle/suite.go
Labels: dco-signoff: yes, approved, size/M, lgtm

#396 refactor: extract truststore encoding to internal package
  pkg/bundle/bundle_test.go
  pkg/bundle/internal/truststore/types.go
  pkg/bundle/internal/truststore/types_test.go
  pkg/bundle/source.go
  pkg/bundle/source_test.go
Labels: dco-signoff: yes, approved, size/L, lgtm

#375 Introduce certificate pool structure and remove multiple encode/decode process
  pkg/bundle/bundle_test.go
  pkg/bundle/internal/truststore/types.go
  pkg/bundle/internal/truststore/types_test.go
  pkg/bundle/source.go
  pkg/bundle/source_test.go
  pkg/fspkg/package.go
  pkg/util/cert_pool.go
  pkg/util/cert_pool_test.go
  pkg/util/pem.go
  pkg/util/pem_test.go
  test/dummy/certificates.go
  test/env/data.go
Labels: dco-signoff: yes, approved, lgtm, size/XL, ok-to-test

#401 Fix example of topologySpreadConstraints to reference trust-manager
  deploy/charts/trust-manager/README.md
  deploy/charts/trust-manager/values.schema.json
  deploy/charts/trust-manager/values.yaml
Labels: dco-signoff: yes, approved, size/XS, lgtm
