Repository cert-manager/trust-manager, pull requests merged in 2024-12, with the labels that each got.

#494 Remove unused Makefile variables
  make/00_mod.mk
Labels: dco-signoff: yes, approved, size/XS, lgtm

#508 Update readme to better reflect what we have today
  README.md
Labels: dco-signoff: yes, approved, size/M, lgtm

#509 [CI] Self-upgrade merging self-upgrade-main into main
  .github/workflows/govulncheck.yaml
  .github/workflows/make-self-upgrade.yaml
  klone.yaml
  make/_shared/go/base/.github/workflows/govulncheck.yaml
  make/_shared/kind/00_kind_image_versions.mk
  make/_shared/repository-base/base/.github/workflows/make-self-upgrade.yaml
  make/_shared/tools/00_mod.mk
Labels: dco-signoff: yes, approved, size/M, lgtm

#516 Manual makefile modules update
  klone.yaml
  make/_shared/kind/00_kind_image_versions.mk
  make/_shared/tools/00_mod.mk
Labels: dco-signoff: yes, approved, size/M, lgtm

#506 Add Helm chart OCI release to GH automation
  .github/workflows/debian-trust-package-release.yaml
  .github/workflows/release.yaml
  RELEASE.md
  klone.yaml
  make/00_mod.mk
  make/02_mod.mk
  make/_shared/helm/helm.mk
Labels: dco-signoff: yes, approved, size/M, lgtm

#519 [CI] Self-upgrade merging self-upgrade-main into main
  .github/workflows/make-self-upgrade.yaml
  klone.yaml
  make/_shared/oci-build/00_mod.mk
  make/_shared/repository-base/base/.github/workflows/make-self-upgrade.yaml
Labels: dco-signoff: yes, approved, size/M, lgtm

#520 [CI] Self-upgrade merging self-upgrade-main into main
  .github/workflows/govulncheck.yaml
  klone.yaml
  make/_shared/go/base/.github/workflows/govulncheck.yaml
Labels: dco-signoff: yes, approved, size/M, lgtm

#523 Add 'fetch-depth: 0' to Debian trust bundle GH checkout action
  .github/workflows/debian-trust-package-release.yaml
  .github/workflows/debian-trust-package-upgrade.yaml
Labels: dco-signoff: yes, approved, lgtm
