Repository cert-manager/trust-manager, pull requests merged in 2024-01, with the labels that each got.

#260 fix: should reconcile targets consistently
  pkg/bundle/sync.go
  test/integration/bundle/suite.go
Labels: dco-signoff: yes, approved, size/M, lgtm

#262 Upgrade dependencies
  go.mod
  go.sum
Labels: dco-signoff: yes, approved, size/XS, lgtm

#264 [release-0.7]: fix flaky tests by introducing komega
  test/integration/bundle/suite.go
Labels: dco-signoff: yes, approved, size/L, lgtm

#266 [release-0.7]: should reconcile targets consistently
  pkg/bundle/sync.go
  test/integration/bundle/suite.go
Labels: dco-signoff: yes, approved, size/M, lgtm

#267 [release-0.7] Bump versions to fix trivy-reported vulns and prepare for release
  Makefile
  deploy/charts/trust-manager/Chart.yaml
  deploy/charts/trust-manager/README.md
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: dco-signoff: yes, approved, size/M, lgtm

#268 Improve makefile comments around image building
  Makefile
Labels: dco-signoff: yes, approved, size/XS, lgtm

#257 fix: apply-configuration gen for Bundle (cluster-scoped)
  pkg/apis/trust/v1alpha1/types_bundle.go
  pkg/applyconfigurations/trust/v1alpha1/bundle.go
Labels: dco-signoff: yes, approved, size/XS, lgtm

#251 Do more of the container build process locally
  Dockerfile
  Makefile
  trust-packages/debian/Containerfile
Labels: dco-signoff: yes, approved, lgtm, size/S

#269 Don't build trust bundle images using make image
  Makefile
Labels: dco-signoff: yes, approved, size/XS, lgtm

#258 Add label selector option for Secret and ConfigMap sources
  deploy/charts/trust-manager/templates/trust.cert-manager.io_bundles.yaml
  deploy/crds/trust.cert-manager.io_bundles.yaml
  pkg/apis/trust/v1alpha1/types_bundle.go
  pkg/apis/trust/v1alpha1/zz_generated.deepcopy.go
  pkg/applyconfigurations/trust/v1alpha1/sourceobjectkeyselector.go
  pkg/bundle/controller.go
  pkg/bundle/sync.go
  pkg/webhook/validation.go
  pkg/webhook/validation_test.go
Labels: dco-signoff: yes, approved, size/L, lgtm, ok-to-test

#273 Add an option to filter expired certificates from bundle
  cmd/trust-manager/app/options/options.go
  deploy/charts/trust-manager/README.md
  deploy/charts/trust-manager/templates/deployment.yaml
  deploy/charts/trust-manager/values.yaml
  pkg/bundle/bundle.go
  pkg/bundle/bundle_test.go
  pkg/bundle/sync.go
  pkg/util/cert_pool.go
  pkg/util/cert_pool_test.go
  pkg/util/pem.go
  pkg/util/pem_test.go
  test/dummy/certificates.go
Labels: dco-signoff: yes, approved, size/L, lgtm, ok-to-test

#275 Test tweaks following #273
  pkg/util/pem_test.go
  test/dummy/certificates.go
  test/dummy/certificates_test.go
Labels: dco-signoff: yes, approved, size/L, lgtm

#277 Bump versions for release, bump deps
  Makefile
  deploy/charts/trust-manager/Chart.yaml
  deploy/charts/trust-manager/README.md
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: dco-signoff: yes, approved, size/M, lgtm

#280 docs: updating chart values.yaml for better comment docs
  deploy/charts/trust-manager/README.md
  deploy/charts/trust-manager/values.yaml
Labels: dco-signoff: yes, approved, size/L, lgtm, ok-to-test
