Repository cert-manager/trust-manager, pull requests merged in 2025-04, with the labels that each got.

#577 Added PKCS12 profile option
  deploy/charts/trust-manager/templates/crd-trust.cert-manager.io_bundles.yaml
  deploy/crds/trust.cert-manager.io_bundles.yaml
  pkg/apis/trust/v1alpha1/types_bundle.go
  pkg/bundle/internal/target/target.go
  pkg/bundle/internal/truststore/types.go
  pkg/bundle/internal/truststore/types_test.go
Labels: dco-signoff: yes, approved, size/M, lgtm, ok-to-test

#583 Fixup PDB namespace population logic
  deploy/charts/trust-manager/templates/poddisruptionbudget.yaml
Labels: dco-signoff: yes, approved, size/XS, lgtm, ok-to-test

#586 [CI] Self-upgrade merging self-upgrade-main into main
  .github/workflows/govulncheck.yaml
  .github/workflows/make-self-upgrade.yaml
  klone.yaml
  make/_shared/go/base/.github/workflows/govulncheck.yaml
  make/_shared/oci-build/00_mod.mk
  make/_shared/oci-build/01_mod.mk
  make/_shared/repository-base/base/.github/workflows/make-self-upgrade.yaml
  make/_shared/tools/00_mod.mk
Labels: dco-signoff: yes, approved, size/M, lgtm

#598 Add generation of applyconfigurations (again)
  make/02_mod.mk
  pkg/applyconfigurations/internal/internal.go
  pkg/applyconfigurations/trust/v1alpha1/additionalformats.go
  pkg/applyconfigurations/trust/v1alpha1/bundle.go
  pkg/applyconfigurations/trust/v1alpha1/bundlecondition.go
  pkg/applyconfigurations/trust/v1alpha1/bundlesource.go
  pkg/applyconfigurations/trust/v1alpha1/bundlespec.go
  pkg/applyconfigurations/trust/v1alpha1/bundlestatus.go
  pkg/applyconfigurations/trust/v1alpha1/bundletarget.go
  pkg/applyconfigurations/trust/v1alpha1/jks.go
  pkg/applyconfigurations/trust/v1alpha1/keyselector.go
  pkg/applyconfigurations/trust/v1alpha1/namespaceselector.go
  pkg/applyconfigurations/trust/v1alpha1/pkcs12.go
  pkg/applyconfigurations/trust/v1alpha1/sourceobjectkeyselector.go
  pkg/applyconfigurations/utils.go
Labels: dco-signoff: yes, approved, size/L, lgtm

#595 Improve webhook TLS config configuration
  cmd/trust-manager/app/app.go
  cmd/trust-manager/app/ciphers_test.go
  cmd/trust-manager/app/options/options.go
Labels: dco-signoff: yes, approved, size/L, lgtm

#602 Fix slightly misleading PKCS#12 profile API docs
  deploy/charts/trust-manager/templates/crd-trust.cert-manager.io_bundles.yaml
  deploy/crds/trust.cert-manager.io_bundles.yaml
  pkg/apis/trust/v1alpha1/types_bundle.go
  pkg/apis/trustmanager/v1alpha2/types_cluster_bundle.go
Labels: dco-signoff: yes, approved, size/M, lgtm

#582 Add support for target annotations and labels
  deploy/charts/trust-manager/templates/crd-trust.cert-manager.io_bundles.yaml
  deploy/crds/trust.cert-manager.io_bundles.yaml
  pkg/apis/trust/v1alpha1/types_bundle.go
  pkg/apis/trust/v1alpha1/zz_generated.conversion.go
  pkg/apis/trust/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/trustmanager/v1alpha2/types_cluster_bundle.go
  pkg/apis/trustmanager/v1alpha2/zz_generated.deepcopy.go
  pkg/applyconfigurations/trust/v1alpha1/bundletarget.go
  pkg/applyconfigurations/trust/v1alpha1/targetmetadata.go
  pkg/applyconfigurations/trust/v1alpha1/targettemplate.go
  pkg/applyconfigurations/trustmanager/v1alpha2/bundletarget.go
  pkg/applyconfigurations/trustmanager/v1alpha2/targetmetadata.go
  pkg/applyconfigurations/trustmanager/v1alpha2/targettemplate.go
  pkg/applyconfigurations/utils.go
  pkg/bundle/bundle_test.go
  pkg/bundle/internal/target/target.go
  pkg/bundle/internal/target/target_test.go
  pkg/webhook/validation.go
  pkg/webhook/validation_test.go
  test/env/data.go
  test/integration/bundle/suite.go
  test/integration/bundle/validation_test.go
Labels: dco-signoff: yes, approved, lgtm, ok-to-test, size/XXL

#609 [CI] Self-upgrade merging self-upgrade-main into main
  .github/workflows/govulncheck.yaml
  klone.yaml
  make/_shared/go/base/.github/workflows/govulncheck.yaml
  make/_shared/oci-build/00_mod.mk
Labels: dco-signoff: yes, approved, size/M, lgtm

#585 Add extraObjects to Helm chart
  deploy/charts/trust-manager/README.md
  deploy/charts/trust-manager/templates/extra-manifests.yaml
  deploy/charts/trust-manager/values.schema.json
  deploy/charts/trust-manager/values.yaml
Labels: dco-signoff: yes, approved, size/M, lgtm, ok-to-test

#613 Add missing LICENSE file
  trust-packages/debian/LICENSE
  trust-packages/debian/LICENSES
Labels: dco-signoff: yes, approved, size/L, lgtm
