Repository cert-manager/trust-manager, pull requests merged in 2025-09, with the labels that each got.

#718 [CI] Self-upgrade merging self-upgrade-main into main
  .github/renovate.json5
  .github/workflows/make-self-upgrade.yaml
  klone.yaml
  make/_shared/repository-base/base-dependabot/.github/renovate.json5
  make/_shared/repository-base/base/.github/workflows/make-self-upgrade.yaml
  make/_shared/tools/00_mod.mk
Labels: dco-signoff: yes, approved, size/L, lgtm

#730 [CI] Self-upgrade merging self-upgrade-main into main
  .github/chainguard/make-self-upgrade.sts.yaml
  .github/chainguard/renovate.sts.yaml
  .github/dependabot.yaml
  .github/renovate.json5
  .github/workflows/make-self-upgrade.yaml
  .github/workflows/renovate.yaml
  klone.yaml
  make/_shared/repository-base/01_mod.mk
  make/_shared/repository-base/base-dependabot/.github/dependabot.yaml
  make/_shared/repository-base/base-dependabot/.github/renovate.json5
  make/_shared/repository-base/base-dependabot/.github/workflows/renovate.yaml
  make/_shared/repository-base/base/.github/chainguard/make-self-upgrade.sts.yaml
  make/_shared/repository-base/base/.github/chainguard/renovate.sts.yaml
  make/_shared/repository-base/base/.github/workflows/make-self-upgrade.yaml
  make/_shared/tools/00_mod.mk
Labels: dco-signoff: yes, approved, size/L, lgtm

#744 feat: add ability to limit the target namespaces managed
  cmd/trust-manager/app/options/options.go
  deploy/charts/trust-manager/README.md
  deploy/charts/trust-manager/templates/_helpers.tpl
  deploy/charts/trust-manager/templates/clusterrole.yaml
  deploy/charts/trust-manager/templates/deployment.yaml
  deploy/charts/trust-manager/templates/rbac-per-namespace.yaml
  deploy/charts/trust-manager/values.schema.json
  deploy/charts/trust-manager/values.yaml
  pkg/bundle/bundle.go
  pkg/bundle/bundle_test.go
  pkg/bundle/controller.go
  pkg/bundle/controller/options.go
Labels: dco-signoff: yes, approved, size/L, lgtm, ok-to-test, tide/merge-method-squash

#751 Bootstrap shared Renovate preset
  .github/renovate.json5
Labels: dco-signoff: yes, approved, size/L, lgtm

#703 Move additional formats handling from source to target
  pkg/bundle/bundle.go
  pkg/bundle/internal/source/source.go
  pkg/bundle/internal/source/source_test.go
  pkg/bundle/internal/target/target.go
  pkg/bundle/internal/target/target_test.go
Labels: dco-signoff: yes, approved, size/L, lgtm, cybr
