Repository cert-manager/trust-manager, pull requests merged in 2025-08, with the labels that each got.

#678 feat: Add hawksight as reviewer
  OWNERS
Labels: dco-signoff: yes, approved, size/XS, lgtm

#668 Add ClusterBundle validating webhook
  pkg/webhook/cluster_bundle.go
  test/integration/bundle/cluster_bundle_validation_test.go
  test/integration/bundle/integration.go
Labels: dco-signoff: yes, approved, size/L, lgtm

#676 feat(helm): Support revisionhistorylimit
  deploy/charts/trust-manager/README.md
  deploy/charts/trust-manager/templates/deployment.yaml
  deploy/charts/trust-manager/values.schema.json
  deploy/charts/trust-manager/values.yaml
Labels: dco-signoff: yes, approved, lgtm, ok-to-test, size/S

#695 [CI] Self-upgrade merging self-upgrade-main into main
  .github/workflows/govulncheck.yaml
  .github/workflows/make-self-upgrade.yaml
  klone.yaml
  make/_shared/boilerplate/01_mod.mk
  make/_shared/boilerplate/base/LICENSE
  make/_shared/go/01_mod.mk
  make/_shared/go/base/.github/workflows/govulncheck.yaml
  make/_shared/helm/helm.mk
  make/_shared/repository-base/01_mod.mk
  make/_shared/repository-base/base/.github/workflows/make-self-upgrade.yaml
  make/_shared/tools/00_mod.mk
Labels: dco-signoff: yes, approved, size/M, lgtm

#710 fix(deps): update kubernetes go deps to v0.34.0
  .github/workflows/renovate.yaml
  LICENSES
  deploy/crds/trust-manager.io_clusterbundles.yaml
  deploy/crds/trust.cert-manager.io_bundles.yaml
  go.mod
  go.sum
  klone.yaml
  make/_shared/kind/00_kind_image_versions.mk
  make/_shared/repository-base/base-dependabot/.github/workflows/renovate.yaml
  make/_shared/tools/00_mod.mk
  pkg/applyconfigurations/internal/internal.go
  pkg/applyconfigurations/trust/v1alpha1/bundle.go
  pkg/applyconfigurations/trustmanager/v1alpha2/clusterbundle.go
  pkg/applyconfigurations/utils.go
Labels: dco-signoff: yes, approved, size/L, lgtm

#712 Eliminate multiple sigs.k8s.io/structured-merge-diff deps
  LICENSES
  go.mod
  go.sum
  pkg/bundle/internal/ssa_client/patch.go
  pkg/bundle/internal/target/target.go
Labels: dco-signoff: yes, approved, lgtm, size/S
