Repository cert-manager/trust-manager, pull requests merged in 2025-02, with the labels that each got.

#543 Add fetch-depth to checkout action
  .github/workflows/debian-trust-package-release-bookworm.yaml
  make/00_debian_bookworm_version.mk
Labels: dco-signoff: yes, approved, size/XS, lgtm

#544 Fix syntax error
  .github/workflows/debian-trust-package-release-bookworm.yaml
  make/00_debian_bookworm_version.mk
Labels: dco-signoff: yes, approved, lgtm, size/S

#545 Copy the other release action
  .github/workflows/debian-trust-package-release-bookworm.yaml
  make/00_debian_bookworm_version.mk
Labels: dco-signoff: yes, approved, lgtm, size/S

#547 Use the debian bookworm package for testing + releases
  deploy/charts/trust-manager/README.md
  deploy/charts/trust-manager/values.schema.json
  deploy/charts/trust-manager/values.yaml
  make/00_mod.mk
  make/test-smoke.mk
Labels: dco-signoff: yes, approved, lgtm, size/S

#485 Migration Design: Rename Bundle to ClusterBundle
  design/20241124-rename-bunde-to-clusterbundle.md
Labels: dco-signoff: yes, approved, size/L, lgtm

#551 Tweak JUnit config for e2e / integration tests
  make/test-integration.mk
  test/env/ginkgo.go
Labels: dco-signoff: yes, approved, lgtm, size/S

#550 Use Context to pass Logger
  cmd/trust-manager/app/app.go
  cmd/trust-manager/app/options/options.go
  pkg/bundle/bundle.go
  pkg/bundle/bundle_test.go
  pkg/bundle/controller.go
  pkg/bundle/internal/target/target.go
  pkg/bundle/internal/target/target_test.go
  pkg/bundle/source.go
  pkg/webhook/validation.go
  pkg/webhook/validation_test.go
  pkg/webhook/webhook.go
  test/integration/bundle/suite.go
  test/smoke/suite_test.go
Labels: dco-signoff: yes, approved, size/L, lgtm

#553 Add fetch-depth:0 to bookworm upgrade job
  .github/workflows/debian-trust-package-upgrade-bookworm.yaml
  RELEASE.md
Labels: dco-signoff: yes, approved, size/XS, lgtm

#555 add leaderElection flag to trust manager
  cmd/trust-manager/app/app.go
  cmd/trust-manager/app/options/options.go
  deploy/charts/trust-manager/README.md
  deploy/charts/trust-manager/templates/deployment.yaml
  deploy/charts/trust-manager/values.schema.json
  deploy/charts/trust-manager/values.yaml
Labels: dco-signoff: yes, approved, size/M, lgtm, ok-to-test

#556 Introduce min-tls and ciphers-suite application options for webhook server
  cmd/trust-manager/app/app.go
  cmd/trust-manager/app/ciphers_test.go
  cmd/trust-manager/app/options/options.go
  deploy/charts/trust-manager/README.md
  deploy/charts/trust-manager/templates/deployment.yaml
  deploy/charts/trust-manager/values.schema.json
  deploy/charts/trust-manager/values.yaml
Labels: dco-signoff: yes, approved, size/L, lgtm, ok-to-test
