Repository cert-manager/trust-manager, pull requests merged in 2025-01, with the labels that each got.

#511 Bump to Go 1.23 (and allow certificates with negative serial numbers)
  go.mod
Labels: dco-signoff: yes, approved, size/XS, lgtm

#515 RELEASE BLOCKER: Add special case handling of cert with negative serial number
  go.mod
  make/test-unit.mk
  pkg/bundle/source.go
  pkg/compat/negative_serial_number.go
  pkg/compat/negative_serial_number_godebug_test.go
  pkg/compat/negative_serial_number_test.go
  pkg/compat/parse_cert.go
  pkg/compat/util_test.go
  pkg/util/cert_pool.go
Labels: dco-signoff: yes, approved, size/L, lgtm

#513 feat(helm): Allow to configure automountServiceAccountToken
  deploy/charts/trust-manager/README.md
  deploy/charts/trust-manager/templates/_helpers.tpl
  deploy/charts/trust-manager/templates/deployment.yaml
  deploy/charts/trust-manager/templates/serviceaccount.yaml
  deploy/charts/trust-manager/values.schema.json
  deploy/charts/trust-manager/values.yaml
Labels: dco-signoff: yes, approved, size/L, lgtm, ok-to-test

#537 [CI] Self-upgrade merging self-upgrade-main into main
  .github/workflows/govulncheck.yaml
  .github/workflows/make-self-upgrade.yaml
  deploy/crds/crds/trust.cert-manager.io_bundles.yaml
  klone.yaml
  make/_shared/go/base/.github/workflows/govulncheck.yaml
  make/_shared/helm/crds.mk
  make/_shared/repository-base/base/.github/workflows/make-self-upgrade.yaml
Labels: dco-signoff: yes, approved, size/L, lgtm

#493 Simplify integration test setup
  make/test-integration.mk
  test/integration/bundle/integration.go
Labels: dco-signoff: yes, approved, lgtm, size/S

#538 Upgrade oci-build makefile module
  klone.yaml
  make/00_mod.mk
  make/_shared/go/01_mod.mk
  make/_shared/oci-build/00_mod.mk
  make/_shared/oci-build/01_mod.mk
  make/debian-trust-package.mk
Labels: dco-signoff: yes, approved, size/M, lgtm
